name: Feature request
description: Suggest a new way to annoy players.
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: Idea
      description: What should the mod do?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is it funny?
